### ISSUE TITLE
UEFI Bootloader crashes on QEMU/KVM on Arch Linux

### ISSUE THREAD

**Issue by NeoChen1024** [xhebox/noname-linux#2]
When I start it with qemu: "qemu-system-x86_64 -smp 4 -enable-kvm  -m 2048 -bios /usr/share/ovmf/ovmf_code_x64.bin"
ISO version: noname 2017.07
sha512: b9b11f5e520161ad0f4f4632842e456bbd9d4ae434caf8a5ca7c2e3e6dad96bf0fbcd752b475b55b0a1ef81451e23ce45fe0c84c0585d4c46c85847771bc7489
My QEMU Reports error message :

--------Messgae Start----------
KVM internal error. Suberror: 1
emulation failure
RAX=0000000000000016 RBX=0000000000000000 RCX=000000007ea6cff8 RDX=000000000000003f
RSI=000000007ea6c838 RDI=000000007eaa7430 RBP=000000007eaa3430 RSP=000000007fee69b0
R8 =000000007ea6c818 R9 =0000000000000820 R10=0000000000000068 R11=0000000000010000
R12=000000007eaa1de0 R13=000000007f3a10c0 R14=0000000000000123 R15=000000007fef9ba0
RIP=00000000000b0000 RFL=00010217 [----APC] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0030 0000000000000000 ffffffff 00c09300 DPL=0 DS   [-WA]
CS =0038 0000000000000000 ffffffff 00a09b00 DPL=0 CS64 [-RA]
SS =0030 0000000000000000 ffffffff 00c09300 DPL=0 DS   [-WA]
DS =0030 0000000000000000 ffffffff 00c09300 DPL=0 DS   [-WA]
FS =0030 0000000000000000 ffffffff 00c09300 DPL=0 DS   [-WA]
GS =0030 0000000000000000 ffffffff 00c09300 DPL=0 DS   [-WA]
LDT=0000 0000000000000000 0000ffff 00008200 DPL=0 LDT
TR =0000 0000000000000000 0000ffff 00008b00 DPL=0 TSS64-busy
GDT=     000000007fe73a98 00000047
IDT=     000000007f6c5018 00000fff
CR0=80010033 CR2=0000000000000000 CR3=000000007fe85000 CR4=00000668
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000 
DR6=00000000ffff0ff0 DR7=0000000000000400
EFER=0000000000000500
Code=00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 <ff> ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
----------------Message End---------------

My Package version:
extra/qemu 2.9.0-2
core/linux 4.11.9-1 (base)
extra/ovmf 1:r21243.3858b4a1ff-1

dmesg:  http://thunix.org/~neo_chen/dmesg

**Comment by xhebox** [comment]
ovmf seems too old and cant work with recent kernels. It's not a bug of noname.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=810163

**Comment by xhebox** [comment]
It's due to syslinux, i dont know why. It works well with iso made by grub-rescue.
