### ISSUE TITLE
Pm-utils: not work on my laptop, need to test

### ISSUE THREAD

**Issue by xhebox** [xhebox/noname-linux#3]
I can't hibernate anyway(suspend is ok). Though i think this is my personal problem , but it would nice if someone could help me :D.

**Comment by rofl0r** [comment]
we use this https://github.com/sabotage-linux/sabotage/blob/master/KEEP/bin/zzz . hth.

**Comment by xhebox** [comment]
zzz worked, that must means pm-utils has something wrong with my distro. Thx, but i miss the point about:
```
sudo ./zzz -Z
No arg for -Z option
```
(sudo ./zzz -Z* is worked)Why it needs a arg?

**Comment by rofl0r** [comment]
i have no idea, the text `"No arg for"` is not in the zzz script, maybe `strace` can help you to find out where it comes from?

**Comment by rofl0r** [comment]
maybe it's your `sudo` program interfering ? i usually use `su -c myprog myargs`. the sudo program sucks quite a lot, imo.
link to our su program: https://github.com/rofl0r/hardcore-utils/blob/master/su.c

**Comment by xhebox** [comment]
@rofl0r not sudo, i've found the source:
```
while getopts hnSzHRZ: opt; do
```
`:` means it needs a arg, a mistake by the original author. The correct version should be:
```
while getopts "hnSzHRZ" opt; do
```

**Comment by xhebox** [comment]
if you could check it with sabotage, then it's safe to close this issue :D

**Comment by rofl0r** [comment]
i just notified the original author in IRC. let's wait for what he's got to say.

**Comment by rofl0r** [comment]
https://github.com/voidlinux/void-runit/commit/9c4f1f35b24ae293fd0205b0814c5342e97a5f67

**Comment by xhebox** [comment]
ok! close :D
