### ISSUE TITLE
What's this musl patch for?

### ISSUE THREAD

**Issue by firasuke** [xhebox/noname-linux#4]
Hey there,

What's this musl patch used for?

https://github.com/xhebox/noname-linux/blob/master/ports/musl/Pkgfile#L21

Is it to provide compatibility with GNU `pthread_setname_np` and `pthread_getname_np` functions?

Also, what are `pthread-stubs` used for?

Thanks for your efforts!

**Comment by xhebox** [comment]
We already have `pthread_setname_np`, but there is no `pthread_getname_np`. I want it for rust. Refer https://www.openwall.com/lists/musl/2021/05/20/8. If I remember it correctly, it is in the mainline already, but not released yet.

`pthread-stubs` provide a pkgconfig file for pthread. It may be deprecated. I'll check later.

**Comment by firasuke** [comment]
I see.

Thanks for the quick reply!
