### ISSUE TITLE
curl: why enable manual after disabling it?

### ISSUE THREAD

**Issue by firasuke** [xhebox/noname-linux#8]
I noticed that you're passing `--enable-manual` to `curl`'s configure script after having passed `--disable-manual`:
https://github.com/xhebox/noname-linux/blob/9986a659b43e49c50910e444a51f224dfaab2d35/ports/curl/Pkgfile#L23

Is this intended?

**Comment by xhebox** [comment]
No.

I believe that I disabled manual because generating manual needs some tools that I don't want to install.

Now it works and I have removed `disable-manual`.

**Comment by firasuke** [comment]
Alright, closing...
